In [1]:
import numpy as np

In [2]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
zeros_arr=np.zeros(5)
zeros_arr

array([0., 0., 0., 0., 0.])

In [4]:
zeros_arr=np.zeros(5,dtype="int")
zeros_arr



array([0, 0, 0, 0, 0])

In [5]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9],[23,45,5]])
arr3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [23, 45,  5]])

In [6]:
arr3.shape

(4, 3)

In [7]:
arr3.ndim

2

In [8]:
arr3.dtype

dtype('int32')

In [9]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=np.swapaxes(a,0,1)

print("Original:\n",a)
print("Swapped:\n",b)

Original:
 [[1 2 3]
 [4 5 6]]
Swapped:
 [[1 4]
 [2 5]
 [3 6]]


In [10]:
arr3.max()

45

In [11]:
arr3.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 23, 45,  5]])

In [12]:
ones_arr=np.ones(5)
ones_arr

array([1., 1., 1., 1., 1.])

In [13]:
ones_arr=np.ones(5,dtype="int")
ones_arr

array([1, 1, 1, 1, 1])