In [1]:
# Name: Kadam Shubham Devidasrao
# Roll No: 73
# Class: T1B

import numpy as np  # Import NumPy library


In [2]:
# Create a 1D array
array1 = np.array([1, 2, 3, 4, 5, 6])
print("Array1:", array1)

# Get size and number of dimensions
print("Size of array1:", array1.size)
print("Dimensions of array1:", array1.ndim)


Array1: [1 2 3 4 5 6]
Size of array1: 6
Dimensions of array1: 1


In [3]:
# Create a 2D array
array2 = np.array([[7, 8, 9], [23, 4, 5]])
print("Array2:\n", array2)
print("Size of array2:", array2.size)
print("Dimensions of array2:", array2.ndim)


Array2:
 [[ 7  8  9]
 [23  4  5]]
Size of array2: 6
Dimensions of array2: 2


In [4]:
# Reshape array1 to 2 rows and 3 columns
reshaped_array1 = array1.reshape(2, 3)
print("Reshaped array1 (2x3):\n", reshaped_array1)


Reshaped array1 (2x3):
 [[1 2 3]
 [4 5 6]]


In [5]:
# Indexing examples
print("Element at index 2 in array1:", array1[2])
print("Last element in array1:", array1[-1])


Element at index 2 in array1: 3
Last element in array1: 6


In [6]:
# Shape of array2
print("Shape of array2:", array2.shape)


Shape of array2: (2, 3)


In [7]:
# Create two 3x3 arrays
array3 = np.array([[1, 2, 3], [4, 5, 6], [8, 9, 7]])
array4 = np.array([[12, 23, 33], [45, 66, 76], [45, 22, 13]])

print("Array3:\n", array3)
print("Array4:\n", array4)


Array3:
 [[1 2 3]
 [4 5 6]
 [8 9 7]]
Array4:
 [[12 23 33]
 [45 66 76]
 [45 22 13]]


In [8]:
# Arithmetic operations
print("Addition:\n", array3 + array4)
print("---------")
print("Subtraction:\n", array3 - array4)
print("---------")
print("Multiplication:\n", array3 * array4)
print("---------")
print("Division:\n", array3 / array4)
print("---------")
print("Power:\n", array3 ** array4)


Addition:
 [[13 25 36]
 [49 71 82]
 [53 31 20]]
---------
Subtraction:
 [[-11 -21 -30]
 [-41 -61 -70]
 [-37 -13  -6]]
---------
Multiplication:
 [[ 12  46  99]
 [180 330 456]
 [360 198  91]]
---------
Division:
 [[0.08333333 0.08695652 0.09090909]
 [0.08888889 0.07575758 0.07894737]
 [0.17777778 0.40909091 0.53846154]]
---------
Power:
 [[          1     8388608 -1504003197]
 [          0 -1319303399           0]
 [          0    51933809 -1895237401]]


In [9]:
# Data type of array3
print("Data type of array3:", array3.dtype)


Data type of array3: int32


In [10]:
# Create array using arange
array6 = np.arange(2, 13)
print("Array6:", array6)


Array6: [ 2  3  4  5  6  7  8  9 10 11 12]


In [11]:
# Minimum value and its index
min_index = np.argmin(array6)
print("Index of minimum value:", min_index)
print("Minimum value:", array6[min_index])


Index of minimum value: 0
Minimum value: 2


In [12]:
# Maximum value and its index
max_index = np.argmax(array6)
print("Index of maximum value:", max_index)
print("Maximum value:", array6[max_index])


Index of maximum value: 10
Maximum value: 12


In [13]:
# Evenly spaced numbers between 0 and 1
arr = np.linspace(0, 1, 5)
print("Evenly spaced numbers from 0 to 1:", arr)


Evenly spaced numbers from 0 to 1: [0.   0.25 0.5  0.75 1.  ]
